# -*- coding: utf-8 -*-
"""dataloader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QKRddtEjwhbIVvuj3j9BRh8GO2st5lDP
"""

import tensorflow as tf
import tensorflow_datasets as tfds

def load_ucf101():
  (x_train, y_train), (x_test, y_test) = tfds.load(name='ucf101', split=['train', 'test'], as_supervised=True, shuffle_files=True)
  x_train, x_test = x_train[:, 0:32, 16:240, 16:240, :], x_test[:, 0:32, 16:240, 16:240, :]
  return x_train, y_train, x_test, y_test